FROM node:20-alpine AS base

WORKDIR /app

COPY package*.json ./

FROM base AS dependencies
RUN npm ci --only=production

FROM base AS build
RUN npm ci
COPY . .

FROM node:20-alpine AS production

WORKDIR /app

COPY --from=dependencies /app/node_modules ./node_modules
COPY --from=build /app .

RUN mkdir -p /app/exports && chmod 777 /app/exports

ENV NODE_ENV=production

CMD ["node", "worker.js"]